# Numpy
- NumPy is the fundamental package for scintific computing in Python.
- It helps to create homogenous array

In [70]:
# Importing NumPy np.array

import numpy as np

a= np.array([1,2,3,4])

print(type(a)) #<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [71]:
# 2D and 3D arrays
#Matrix
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [72]:
#Tensor array
c= np.array([[[1,2],[4,5]],[[5,6],[7,4]]])
print(c)

[[[1 2]
  [4 5]]

 [[5 6]
  [7 4]]]


In [73]:
#Dtype

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [74]:
np.array([1,2,0],dtype=bool)

array([ True,  True, False])

In [75]:
#np.arange
np.arange(1,11) # array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
#np.arange with Reshape

np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
# PRE initialized arrays exampls

#np.ones and np.zeros

np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
# np.random
np.random.random((3,4))

array([[0.99686045, 0.6704524 , 0.79451704, 0.56076503],
       [0.92451926, 0.71589517, 0.38381393, 0.84918142],
       [0.89955053, 0.51660687, 0.14911474, 0.77393307]])

In [80]:
# np.linspace => Prints Linear separable array
# lower range, upper range, number of items you want
np.linspace(0,11,5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [81]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array attributes

In [82]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [83]:
# ndim
a2.ndim

2

In [84]:
# shape 
a2.shape # (3,4)

(3, 4)

In [85]:
# size

a2.size # 12

12

In [86]:
#itemsize
a1.itemsize # 

4

<h2>Changing DataType</h2>

In [87]:
# astype
a3.astype(np.int16)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

# Array Operations 

In [88]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [89]:
# Scalar operations

#* Arithmatic 

a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [90]:
# Relational operators 

a2>15 

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
# Vector operations
print(f'a1 = {a1}')

print(f'a2 = {a2}')

a1*a2

a1 = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2 = [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Functions

In [92]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)




In [93]:
# max/min/sum/prod
# np.max .....
# 0 in axis means col and 1 in axis means row
np.prod(a1, axis=0)

array([229824.,  22400.,  26640.])

In [94]:
#MEAN / MEDIAN / STD /VAR

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))

47.77777777777778
36.0
28.774131043073233


In [95]:
# trigonometric function

np.sin(np.pi/2)

1.0

In [96]:
# Dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [97]:
# log and exponents

np.exp(a1)

array([[4.31123155e+15, 5.54062238e+34, 4.31123155e+15],
       [1.01480039e+33, 4.85165195e+08, 1.37338298e+32],
       [3.02507732e+36, 1.20260428e+06, 2.20264658e+04]])

In [98]:
# round/ floor/ ceil

np.round(a1)

array([[36., 80., 36.],
       [76., 20., 74.],
       [84., 14., 10.]])

#  INDEXING & SLICING 

In [99]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [100]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a1[-1]


9

In [102]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a2[1,2]

6

In [104]:
a2[2,3]

11

In [105]:
a2[1,0]

4

In [106]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [107]:
a3[1,0,1]

5

In [108]:
a3[0,1,0]

2

In [109]:
a3[0,0,0]

0

In [110]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
a1[2:5]

array([2, 3, 4])

In [112]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
a2[0,:] # 0r a2[0]

array([0, 1, 2, 3])

In [114]:
a2[:,2]

array([ 2,  6, 10])

In [115]:
a2[1:,1:3]


array([[ 5,  6],
       [ 9, 10]])

In [116]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [117]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [118]:
a2[1,::3]

array([4, 7])

In [119]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [120]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [122]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [123]:
a3[0,1]

array([3, 4, 5])

In [124]:
a3[1,:,1]

array([10, 13, 16])

In [125]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [126]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# ITERATING

In [127]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [128]:
a2 

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [129]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [130]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [131]:
# important funtion -> nditer which every iteration

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [132]:
# Reshaping 


a2
np.transpose(a2)


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [133]:
a2.T


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [134]:
# ravel -> make the array 1d 

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [138]:
# horizontally Stacking 
a4= np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [140]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [141]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [142]:
# Horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [149]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [150]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]