In [76]:
# np.sort
import numpy as np

In [77]:
a= np.random.randint(1,100,15)
a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [78]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[18, 82, 23, 63],
       [54, 33, 16, 54],
       [22, 50,  7, 11],
       [54, 34, 81, 27],
       [82, 84, 43,  5],
       [69, 57, 49, 88]])

In [79]:
np.sort(a)

array([28, 30, 32, 46, 59, 62, 66, 67, 71, 72, 74, 83, 89, 90, 94])

In [80]:
np.sort(a)[::-1]

array([94, 90, 89, 83, 74, 72, 71, 67, 66, 62, 59, 46, 32, 30, 28])

In [81]:
np.sort(b)

array([[18, 23, 63, 82],
       [16, 33, 54, 54],
       [ 7, 11, 22, 50],
       [27, 34, 54, 81],
       [ 5, 43, 82, 84],
       [49, 57, 69, 88]])

In [82]:
np.sort(b,axis=0)

array([[18, 33,  7,  5],
       [22, 34, 16, 11],
       [54, 50, 23, 27],
       [54, 57, 43, 54],
       [69, 82, 49, 63],
       [82, 84, 81, 88]])

In [83]:
# Append function 

np.append(a,100)


array([ 62,  71,  46,  74,  28,  59,  66,  32,  90,  94,  30,  72,  67,
        83,  89, 100])

In [84]:
np.append(b,np.ones((b.shape[0],1)))

array([18., 82., 23., 63., 54., 33., 16., 54., 22., 50.,  7., 11., 54.,
       34., 81., 27., 82., 84., 43.,  5., 69., 57., 49., 88.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [85]:
# NP. concatenate

c= np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [86]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [87]:
np.concatenate((c,d), axis=0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [88]:
# Np.unique

e= np.array([1,1,2,2,2,3,4,3,4,4,5,5,5])

np.unique(e)

array([1, 2, 3, 4, 5])

In [89]:
#np.expand_dims

a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [90]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [91]:
# Np.where = find all indices woth value greater than 50
a


array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [92]:
np.where(a>50)

(array([ 0,  1,  3,  5,  6,  8,  9, 11, 12, 13, 14], dtype=int64),)

In [93]:
# replace all values greater than 50 with 0

# np.where(condition,true,false)

np.where(a>50,0,a)

array([ 0,  0, 46,  0, 28,  0,  0, 32,  0,  0, 30,  0,  0,  0,  0])

In [94]:
np.where(a%2==0,0,a)

array([ 0, 71,  0,  0,  0, 59,  0,  0,  0,  0,  0,  0, 67, 83, 89])

In [95]:
#np.argmax

a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [96]:
np.argmax(a)

9

In [97]:
b

array([[18, 82, 23, 63],
       [54, 33, 16, 54],
       [22, 50,  7, 11],
       [54, 34, 81, 27],
       [82, 84, 43,  5],
       [69, 57, 49, 88]])

In [98]:
np.argmax(b,axis=0)
#* same works with np.argmin

array([4, 4, 3, 5], dtype=int64)

In [99]:
#np.cumsum
a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [100]:
np.cumsum(a)

array([ 62, 133, 179, 253, 281, 340, 406, 438, 528, 622, 652, 724, 791,
       874, 963])

In [101]:
b

array([[18, 82, 23, 63],
       [54, 33, 16, 54],
       [22, 50,  7, 11],
       [54, 34, 81, 27],
       [82, 84, 43,  5],
       [69, 57, 49, 88]])

In [102]:
np.cumsum(b)

array([  18,  100,  123,  186,  240,  273,  289,  343,  365,  415,  422,
        433,  487,  521,  602,  629,  711,  795,  838,  843,  912,  969,
       1018, 1106])

In [103]:
np.cumsum(b,axis=0)

array([[ 18,  82,  23,  63],
       [ 72, 115,  39, 117],
       [ 94, 165,  46, 128],
       [148, 199, 127, 155],
       [230, 283, 170, 160],
       [299, 340, 219, 248]])

In [104]:
# nm.cumprod
a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [105]:
np.cumprod(a)

array([         62,        4402,      202492,    14984408,   419563424,
       -1015561760,  1692400576, -1677756416,  -674222080,  1047633920,
        1364246528,  -558497792,  1235353600,  -544866304, -1248460800])

In [106]:
# HISTOGRAM
a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [107]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 0, 1, 2, 1, 1, 3, 3, 2, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [110]:
# Coefficients and corelations

salary= np.array([20000,40000,60000,80000])
expeirence= np.array([1,3,2,4])

np.corrcoef(salary,expeirence)

array([[1. , 0.8],
       [0.8, 1. ]])

In [111]:
#np.isin

a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [112]:
items=[10,20,30,40,50,60,70,80,90,100]
np.isin(a, items)

array([False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False])

In [113]:
a[np.isin(a, items)]

array([90, 30])

In [114]:
# FLIP
a

array([62, 71, 46, 74, 28, 59, 66, 32, 90, 94, 30, 72, 67, 83, 89])

In [115]:
np.flip(a)

array([89, 83, 67, 72, 30, 94, 90, 32, 66, 59, 28, 74, 46, 71, 62])

In [116]:
b

array([[18, 82, 23, 63],
       [54, 33, 16, 54],
       [22, 50,  7, 11],
       [54, 34, 81, 27],
       [82, 84, 43,  5],
       [69, 57, 49, 88]])

In [117]:
np.flip(b)

array([[88, 49, 57, 69],
       [ 5, 43, 84, 82],
       [27, 81, 34, 54],
       [11,  7, 50, 22],
       [54, 16, 33, 54],
       [63, 23, 82, 18]])

In [119]:
# PUT
a
np.put(a,[0,1],[110,111])

In [120]:
a

array([110, 111,  46,  74,  28,  59,  66,  32,  90,  94,  30,  72,  67,
        83,  89])

In [122]:
#Delete 
# parameter(variable,[index])
np.delete(a,[1])

array([110,  46,  74,  28,  59,  66,  32,  90,  94,  30,  72,  67,  83,
        89])

In [129]:
# CLIP

a


array([110, 111,  46,  74,  28,  59,  66,  32,  90,  94,  30,  72,  67,
        83,  89])

In [130]:
np.clip(a,a_min=50,a_max=100)


array([100, 100,  50,  74,  50,  59,  66,  50,  90,  94,  50,  72,  67,
        83,  89])